version: '3.8'
services:
  nginx:
    build:
      context: .
    ports:
      - '3000:80'
    volumes:
      - ../../font-end-nextjs-cinema/.next/standalone/.next/server/app:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf


